### ISSUE TITLE
Employee TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/cash_register#10]
- [x] Track shifts
- [x] Add salary
- [x] Calculate payment
- [x] Allow removal of employees
- [x] Allow employees to be promoted in status
- [x] Have a clock in and clock out function that tracks shifts of those not logged in
- [x] Tests for clock in and out and update status
