### ISSUE TITLE
Transaction TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/cash_register#4]
- [x] Make it look better, show price
- [x] Write tests
- [x] Have a cash out button that tells how much change to give and closes the transaction
- [x] Have modifications on transaction items
- [x] "Print receipt" function
- [x] Let managers cancel transactions
- [x] Be able to remove items from transactions
- [x] Warn if not enough money is given and stop transaction from closing
- [x] Have transaction tied to a user so that multiple transactions can be happening at once
- [x] If item is deleted, transaction.item no longer exists
