### ISSUE TITLE
Modification and Modification Options TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/cash_register#6]
- [x] Find a way to put modifications onto multiple items at once
- [x] Tests
- [x] Find a way to add multiple modifications to an item at once
- [x] Allow removal of modification from items
- [x] Charge extra for premiums
- [x] Have a limit for how many can be added to items
- [x] Remove modifications from items in edit page
